resourceLimits:
  cpu: 1000m
  memory: 512Mi

cronjob:
  # The websocket connect URI for the service being watchinated
  # example: wss://foo.bar.com/websocket
  consumerUri:
  image:
  schedule: "*/1 * * * *"

namespace: watchinator
